#!/bin/bash
#
# for Intel (Sandy/Ivy)Bridge 
#		(does not work with kernel 3.2 on IvyBridge)
#
# ...add condition for HDMI
#
echo 'Monitor-Auto-Setup script is starting...'

# scrape displays for what is connected
displays="$(xrandr -q)"

# identify architecture
if [[ $(grep 'IvyBridge' /var/log/dmesg) != $NULL ]]; then
	echo 'Detected IvyBridge Architecture'
	# check for dock displays
	if [[ $displays == *"DP2 connected"*"DP3 connected"* ]]; then
		echo '=== LAPTOP IS PROBABLY DOCKED w/ TWO DISPLAYS ==='
		
		## setup dock displays
		xrandr --verbose --output DP3 --off;
		xrandr --verbose --output DP2 --off;
		xrandr --verbose --output LVDS1 --off;
		echo '>>> LVDS1, DP2, DP3  off <<<'
		
		xrandr --verbose --fb 3840x1200 --output DP2 --auto --pos 0x0 --crtc 0;
		xrandr --verbose --output DP3 --auto --right-of DP2 --crtc 1;
		echo '<<< DP2, DP3  on >>>'
	elif [[ $displays == *"DP2 connected"* ]]; then
		echo '=== LAPTOP IS PROBABLY DOCKED w/ ONE DISPLAY ==='
		
		## setup dock display
		xrandr --verbose --output DP3 --off;
		xrandr --verbose --output DP2 --off;
		xrandr --verbose --output LVDS1 --off;
		echo '>>> LVDS1, DP2, DP3  off <<<'
		
		xrandr --verbose --fb 1920x1200 --output DP2 --auto --pos 0x0 --crtc 0;
		echo '<<< DP2  on >>>'
	elif [[ $displays == *"DP3 connected"* ]]; then
		echo '=== LAPTOP IS PROBABLY DOCKED w/ ONE DISPLAY ==='
		
		## setup dock display
		xrandr --verbose --output DP3 --off;
		xrandr --verbose --output DP2 --off;
		xrandr --verbose --output LVDS1 --off;
		echo '>>> LVDS1, DP2, DP3  off <<<'
		
		xrandr --verbose --fb 1920x1200 --output DP3 --auto --pos 0x0 --crtc 0;
		echo '<<< DP3  on >>>'
	elif [[ $displays == *"DP1 connected"* ]]; then
		echo '=== DP++ EXTERNAL MONITOR ==='
		xrandr --output LVDS1 --auto --crtc 0 --output DP1 --auto --crtc 1 --right-of LVDS1;
	else
		# not docked and no DP++ monitor attached
		echo '=== NO EXTERNAL DISPLAYS ==='
		
	fi

elif [[ $(grep 'SandyBridge' /var/log/dmesg) != $NULL ]]; then
	echo 'Detected SandyBridge Architecture'
	# check initial displays
	if [[ $displays == *"DP2 connected"*"DP3 connected"* ]]; then
		echo '=== LAPTOP IS PROBABLY DOCKED ==='
		xrandr --verbose --output LVDS1 --off --output DP2 --auto --pos 0x0 --output DP3 --auto --pos 1920x0 --right-of DP2;
	elif [[ $displays == *"DP2 connected"* ]]; then
		echo '=== LAPTOP IS PROBABLY DOCKED w/ ONE DISPLAY ==='
		xrandr --verbose --output LVDS1 --off --output DP2 --auto --pos 0x0;
		echo '<<< DP2  on >>>'
	elif [[ $displays == *"DP3 connected"* ]]; then
		echo '=== LAPTOP IS PROBABLY DOCKED w/ ONE DISPLAY ==='
		xrandr --verbose --output LVDS1 --off --output DP3 --auto --pos 0x0;
		echo '<<< DP3  on >>>'
	elif [[ $displays == *"DP1 connected"* ]]; then
		echo '=== DP++ EXTERNAL MONITOR ==='
		xrandr --output LVDS1 --auto --output DP1 --auto --crtc 1 --right-of LVDS1;
	else
		# not docked and no DP++ monitor attached
		echo '=== NO EXTERNAL DISPLAYS ==='
		
	fi

else
	echo ' '
	echo 'Did NOT detect (Sandy/Ivy)Bridge Architecture (probably on a VM...)'
	echo ' '
fi

# exit
echo 'Monitor-Auto-Setup script has finished.'

